CC26xx Driver Library: [ddi] Digital to Digital Interface
[ddi] Digital to Digital Interface
Analog Domain
Functions
static void AuxAdiDdiSafeWrite (uint32_t nAddr, uint32_t nData, uint32_t nSize)
Safely write to AUX ADI/DDI interfaces using a semaphore.
static uint32_t AuxAdiDdiSafeRead (uint32_t nAddr, uint32_t nSize)
Safely read from AUX ADI/DDI interfaces using a semaphore.
static uint32_t DDI32RegRead (uint32_t ui32Base, uint32_t ui32Reg)
Read the value in a 32 bit register.
static void DDI32BitsSet (uint32_t ui32Base, uint32_t ui32Reg, uint32_t ui32Val)
Set specific bits in a DDI slave register.
static void DDI32BitsClear (uint32_t ui32Base, uint32_t ui32Reg, uint32_t ui32Val)
Clear specific bits in a 32 bit DDI register.
static void DDI8SetValBit (uint32_t ui32Base, uint32_t ui32Reg, uint32_t ui32Byte, uint16_t ui16Mask, uint16_t ui16Val)
Set a value on any 8 bits inside a 32 bit register in the DDI slave.
static void DDI16SetValBit (uint32_t ui32Base, uint32_t ui32Reg, bool bWriteHigh, uint32_t ui32Mask, uint32_t ui32Val)
Set a value on any 16 bits inside a 32 bit register aligned on a half-word boundary in the DDI slave.
void DDI32RegWrite (uint32_t ui32Base, uint32_t ui32Reg, uint32_t ui32Val)
Write a 32 bit value to a register in the DDI slave.
void DDI16BitWrite (uint32_t ui32Base, uint32_t ui32Reg, uint32_t ui32Mask, uint32_t ui32WrData)
Write a single bit using a 16-bit maskable write.
void DDI16BitfieldWrite (uint32_t ui32Base, uint32_t ui32Reg, uint32_t ui32Mask, uint32_t ui32Shift, uint16_t ui32Data)
Write a bit field via the DDI using 16-bit maskable write.
uint16_t DDI16BitRead (uint32_t ui32Base, uint32_t ui32Reg, uint32_t ui32Mask)
Read a bit via the DDI using 16-bit read.
uint16_t DDI16BitfieldRead (uint32_t ui32Base, uint32_t ui32Reg, uint32_t ui32Mask, uint32_t ui32Shift)
Read a bitfield via the DDI using 16-bit read.
Detailed Description
Introduction
API
The API functions can be grouped like this:
Write:
Direct (all bits):
DDI32RegWrite()
Set individual bits:
DDI32BitsSet()
Clear individual bits:
DDI32BitsClear()
Masked:
DDI8SetValBit()
DDI16SetValBit()
Special functions using masked write:
DDI16BitWrite()
DDI16BitfieldWrite()
Read:
Direct (all bits):
DDI32RegRead()
Special functions using masked read:
DDI16BitRead()
DDI16BitfieldRead()
AUX access using semaphores (used by both ADI and DDI APIs when necessary):
AuxAdiDdiSafeRead()
AuxAdiDdiSafeWrite()
Function Documentation
static uint32_t AuxAdiDdiSafeRead (uint32_t nAddr, uint32_t nSize) inline static
Safely read from AUX ADI/DDI interfaces using a semaphore.
Note
Both the AUX module and the clock for the AUX SMPH module must be enabled before calling this function.
Parameters
nAddr is the register address.
nSize is the register access size in bytes.
Returns
Returns the data read.
Referenced by ADI16RegRead(), ADI32RegRead(), ADI8RegRead(), DDI16BitfieldRead(), DDI16BitRead(), and DDI32RegRead().
 {
     uint32_t nRet;
     // Disable interrupts and remember whether to re-enable
     bool bIrqEnabled = !CPUcpsid();
     // Acquire semaphore for accessing ADI/DDI in AUX, perform access, release semaphore
     while (!HWREG(AUX_SMPH_BASE + AUX_SMPH_O_SMPH0));
     switch (nSize) {
     case 1:             nRet = HWREGB(nAddr); break;
     case 2:             nRet = HWREGH(nAddr); break;
     case 4: default:    nRet = HWREG(nAddr); break;
     }
     HWREG(AUX_SMPH_BASE + AUX_SMPH_O_SMPH0) = 1;
     // Restore interrupt enable
     if (bIrqEnabled) {
         CPUcpsie();
     }
     return nRet;
 }
static void AuxAdiDdiSafeWrite (uint32_t nAddr, uint32_t nData, uint32_t nSize) inline static
Safely write to AUX ADI/DDI interfaces using a semaphore.
Note
Both the AUX module and the clock for the AUX SMPH module must be enabled before calling this function.
Parameters
nAddr is the register address.
nData is the data to write to the register.
nSize is the register access size in bytes.
Returns
None
Referenced by ADI16BitsClear(), ADI16BitsSet(), ADI16RegWrite(), ADI16SetValBit(), ADI32BitsClear(), ADI32BitsSet(), ADI32RegWrite(), ADI4SetValBit(), ADI8BitsClear(), ADI8BitsSet(), ADI8RegWrite(), ADI8SetValBit(), DDI16BitfieldWrite(), DDI16BitWrite(), DDI16SetValBit(), DDI32BitsClear(), DDI32BitsSet(), DDI32RegWrite(), and DDI8SetValBit().
 {
     // Disable interrupts and remember whether to re-enable
     bool bIrqEnabled = !CPUcpsid();
     // Acquire semaphore for accessing ADI/DDI in AUX, perform access, release semaphore
     while (!HWREG(AUX_SMPH_BASE + AUX_SMPH_O_SMPH0));
     switch (nSize) {
     case 1:             HWREGB(nAddr) = (uint8_t)nData; break;
     case 2:             HWREGH(nAddr) = (uint16_t)nData; break;
     case 4: default:    HWREG(nAddr)  = nData; break;
     }
     HWREG(AUX_SMPH_BASE + AUX_SMPH_O_SMPH0) = 1;
     // Restore interrupt enable
     if (bIrqEnabled) {
         CPUcpsie();
     }
 }
uint16_t DDI16BitfieldRead (uint32_t ui32Base, uint32_t ui32Reg, uint32_t ui32Mask, uint32_t ui32Shift)
Read a bitfield via the DDI using 16-bit read.
Requires that bit fields do not space the low/high word boundary.
Note
Both the AUX module and the clock for the AUX SMPH module must be enabled before calling this function.
Parameters
ui32Base is the base address of the DDI port.
ui32Reg is register to access.
ui32Mask is the mask defining which of the 16 bits that should be overwritten. The mask must be defined in the lower half of the 32 bits.
ui32Shift defines the required shift of the data to align with bit 0.
Returns
Returns data aligned to bit 0.
Referenced by OSCClockSourceGet(), and OSCHfSourceReady().
 {
     uint32_t ui32RegAddr;
     uint16_t ui16Data;
     // Check the arguments.
     ASSERT(DDIBaseValid(ui32Base));
     // Calculate the register address.
     ui32RegAddr = ui32Base + ui32Reg + DDI_O_DIR;
     // Adjust for target bit in high half of the word.
     if(ui32Shift >= 16)
     {
         ui32Shift = ui32Shift - 16;
         ui32RegAddr += 2;
         ui32Mask = ui32Mask >> 16;
     }
     // Read the register.
     ui16Data = AuxAdiDdiSafeRead(ui32RegAddr, 2);
     // Mask data and shift into place.
     ui16Data &= ui32Mask;
     ui16Data >>= ui32Shift;
     // Return data.
     return(ui16Data);
 }
void DDI16BitfieldWrite (uint32_t ui32Base, uint32_t ui32Reg, uint32_t ui32Mask, uint32_t ui32Shift, uint16_t ui32Data)
Write a bit field via the DDI using 16-bit maskable write.
Requires that bitfields not space the low/high word boundary.
Note
Both the AUX module and the clock for the AUX SMPH module must be enabled before calling this function.
Parameters
ui32Base is the base address of the DDI port.
ui32Reg is register to access.
ui32Mask is the mask defining which of the 16 bits that should be overwritten. The mask must be defined in the lower half of the 32 bits.
ui32Shift
ui32Data
Returns
None
Referenced by OSCClockLossEventDisable(), OSCClockLossEventEnable(), OSCClockSourceSet(), and SetupAfterColdResetWakeupFromShutDownCfg2().
 {
     uint32_t ui32RegAddr;
     uint32_t ui32WrData;
     // Check the arguments.
     ASSERT(DDIBaseValid(ui32Base));
     // 16-bit target is on 32-bit boundary so double offset.
     ui32RegAddr = ui32Base + (ui32Reg << 1) + DDI_O_MASK16B;
     // Adjust for target bit in high half of the word.
     if(ui32Shift >= 16)
     {
         ui32Shift = ui32Shift - 16;
         ui32RegAddr += 4;
         ui32Mask = ui32Mask >> 16;
     }
     // Shift data in to position.
     ui32WrData = ui32Data << ui32Shift;
     // Write data.
     AuxAdiDdiSafeWrite(ui32RegAddr, (ui32Mask << 16) | ui32WrData, 4);
 }
uint16_t DDI16BitRead (uint32_t ui32Base, uint32_t ui32Reg, uint32_t ui32Mask)
Read a bit via the DDI using 16-bit read.
Note
Both the AUX module and the clock for the AUX SMPH module must be enabled before calling this function.
Parameters
ui32Base is the base address of the DDI module.
ui32Reg is the register to read.
ui32Mask defines the bit which should be read.
Returns
Returns a zero if bit selected by mask is '0'. Else returns the mask.
 {
     uint32_t ui32RegAddr;
     uint16_t ui16Data;
     // Check the arguments.
     ASSERT(DDIBaseValid(ui32Base));
     // Calculate the address of the register.
     ui32RegAddr = ui32Base + ui32Reg + DDI_O_DIR;
     // Adjust for target bit in high half of the word.
     if(ui32Mask & 0xFFFF0000)
     {
         ui32RegAddr += 2;
         ui32Mask = ui32Mask >> 16;
     }
     // Read a halfword on the DDI interface.
     ui16Data = AuxAdiDdiSafeRead(ui32RegAddr, 2);
     // Mask data.
     ui16Data = ui16Data & ui32Mask;
     // Return masked data.
     return(ui16Data);
 }
void DDI16BitWrite (uint32_t ui32Base, uint32_t ui32Reg, uint32_t ui32Mask, uint32_t ui32WrData)
Write a single bit using a 16-bit maskable write.
A '1' is written to the bit if ui32WrData is non-zero, else a '0' is written.
Note
Both the AUX module and the clock for the AUX SMPH module must be enabled before calling this function.
Parameters
ui32Base is the base address of the DDI port.
ui32Reg is register to access.
ui32Mask is the mask defining which of the 16 bit that should be overwritten. The mask must be defined in the lower half of the 32 bits.
ui32WrData is the value to write. The value must be defined in the lower half of the 32 bits.
Returns
None
Referenced by OSCXHfPowerModeSet().
 {
     uint32_t ui32RegAddr;
     uint32_t ui32Data;
     // Check the arguments.
     ASSERT(DDIBaseValid(ui32Base));
     ASSERT(!((ui32Mask & 0xFFFF0000) ^ (ui32Mask & 0x0000FFFF)));
     ASSERT(!(ui32WrData & 0xFFFF0000));
     // DDI 16-bit target is on 32-bit boundary so double offset
     ui32RegAddr = ui32Base + (ui32Reg << 1) + DDI_O_MASK16B;
     // Adjust for target bit in high half of the word.
     if(ui32Mask & 0xFFFF0000)
     {
         ui32RegAddr += 4;
         ui32Mask >>= 16;
     }
     // Write mask if data is not zero (to set mask bit), else write '0'.
     ui32Data = ui32WrData ? ui32Mask : 0x0;
     // Update the register.
     AuxAdiDdiSafeWrite(ui32RegAddr, (ui32Mask << 16) | ui32Data, 4);
 }
static void DDI16SetValBit (uint32_t ui32Base, uint32_t ui32Reg, bool bWriteHigh, uint32_t ui32Mask, uint32_t ui32Val) inline static
Set a value on any 16 bits inside a 32 bit register aligned on a half-word boundary in the DDI slave.
This function allows 16 bit masked access to the DDI slave registers.
Use this function to write any value in the range 0-15 bits aligned on a half-word boundary. Fx. for writing the value 0b101 to bits 1-3 set ui32Val = 0x000A and ui32Mask = 0x000E. Bits 0 and 5-15 will not be affected by the operation, as long as the corresponding bits are not set in the ui32Mask.
Note
Both the AUX module and the clock for the AUX SMPH module must be enabled before calling this function.
Parameters
ui32Base is the base address of the DDI port.
ui32Reg is register to access.
bWriteHigh defines which part of the register to write in.
ui32Mask is the mask defining which of the 16 bit that should be overwritten. The mask must be defined in the lower half of the 32 bits.
ui32Val is the value to write. The value must be defined in the lower half of the 32 bits.
Returns
None
 {
     uint32_t ui32RegOffset;
     // Check the arguments.
     ASSERT(DDIBaseValid(ui32Base));
     ASSERT(ui32Reg < DDI_SLAVE_REGS);
     ASSERT(!(ui32Val & 0xFFFF0000));
     ASSERT(!(ui32Mask & 0xFFFF0000));
     // Get the correct address of the first register used for setting bits
     // in the DDI slave.
     ui32RegOffset = DDI_O_MASK16B + (ui32Reg << 1) + (bWriteHigh ? 4 : 0);
     // Set the selected bits.
     AuxAdiDdiSafeWrite(ui32Base + ui32RegOffset, (ui32Mask << 16) | ui32Val, 4);
 }
static void DDI32BitsClear (uint32_t ui32Base, uint32_t ui32Reg, uint32_t ui32Val) inline static
Clear specific bits in a 32 bit DDI register.
This function will clear bits in a register in the analog domain.
Note
Both the AUX module and the clock for the AUX SMPH module must be enabled before calling this function.
Parameters
ui32Base is DDI base address.
ui32Reg is the base registers to clear the bits in.
ui32Val is the 32 bit one-hot encoded value specifying which bits to clear in the register.
Returns
None
 {
     uint32_t ui32RegOffset;
     // Check the arguments.
     ASSERT(DDIBaseValid(ui32Base));
     ASSERT(ui32Reg < DDI_SLAVE_REGS);
     // Get the correct address of the first register used for setting bits
     // in the DDI slave.
     ui32RegOffset = DDI_O_CLR;
     // Clear the selected bits.
     AuxAdiDdiSafeWrite(ui32Base + ui32RegOffset + ui32Reg, ui32Val, 4);
 }
static void DDI32BitsSet (uint32_t ui32Base, uint32_t ui32Reg, uint32_t ui32Val) inline static
Set specific bits in a DDI slave register.
This function will set bits in a register in the analog domain.
Note
This operation is write only for the specified register. This function is used to set bits in specific register in the DDI slave. Only bits in the selected register are affected by the operation.
Both the AUX module and the clock for the AUX SMPH module must be enabled before calling this function.
Parameters
ui32Base is DDI base address.
ui32Reg is the base register to assert the bits in.
ui32Val is the 32 bit one-hot encoded value specifying which bits to set in the register.
Returns
None
 {
     uint32_t ui32RegOffset;
     // Check the arguments.
     ASSERT(DDIBaseValid(ui32Base));
     ASSERT(ui32Reg < DDI_SLAVE_REGS);
     // Get the correct address of the first register used for setting bits
     // in the DDI slave.
     ui32RegOffset = DDI_O_SET;
     // Set the selected bits.
     AuxAdiDdiSafeWrite(ui32Base + ui32RegOffset + ui32Reg, ui32Val, 4);
 }
static uint32_t DDI32RegRead (uint32_t ui32Base, uint32_t ui32Reg) inline static
Read the value in a 32 bit register.
This function will read a register in the analog domain and return the value as an uint32_t.
Note
Both the AUX module and the clock for the AUX SMPH module must be enabled before calling this function.
Parameters
ui32Base is DDI base address.
ui32Reg is the 32 bit register to read.
Returns
Returns the 32 bit value of the analog register.
 {
     // Check the arguments.
     ASSERT(DDIBaseValid(ui32Base));
     ASSERT(ui32Reg < DDI_SLAVE_REGS);
     // Read the register and return the value.
     return AuxAdiDdiSafeRead(ui32Base + ui32Reg, 4);
 }
void DDI32RegWrite (uint32_t ui32Base, uint32_t ui32Reg, uint32_t ui32Val)
Write a 32 bit value to a register in the DDI slave.
This function will write a value to a register in the analog domain.
Note
This operation is write only for the specified register. No conservation of the previous value of the register will be kept (i.e. this is NOT read-modify-write on the register).
Both the AUX module and the clock for the AUX SMPH module must be enabled before calling this function.
Parameters
ui32Base is DDI base address.
ui32Reg is the register to write.
ui32Val is the 32 bit value to write to the register.
Returns
None
Referenced by SetupAfterColdResetWakeupFromShutDownCfg2().
 {
     // Check the arguments.
     ASSERT(DDIBaseValid(ui32Base));
     ASSERT(ui32Reg < DDI_SLAVE_REGS);
     // Write the value to the register.
     AuxAdiDdiSafeWrite(ui32Base + ui32Reg, ui32Val, 4);
 }
static void DDI8SetValBit (uint32_t ui32Base, uint32_t ui32Reg, uint32_t ui32Byte, uint16_t ui16Mask, uint16_t ui16Val) inline static
Set a value on any 8 bits inside a 32 bit register in the DDI slave.
This function allows byte (8 bit access) to the DDI slave registers.
Use this function to write any value in the range 0-7 bits aligned on a byte boundary. Fx. for writing the value 0b101 to bits 1-3 set ui16Val = 0x0A and ui16Mask = 0x0E. Bits 0 and 5-7 will not be affected by the operation, as long as the corresponding bits are not set in the ui16Mask.
Note
Both the AUX module and the clock for the AUX SMPH module must be enabled before calling this function.
Parameters
ui32Base is the base address of the DDI port.
ui32Reg is the Least Significant Register in the DDI slave that will be affected by the write operation.
ui32Byte is the byte number to access within the 32 bit register.
ui16Mask is the mask defining which of the 8 bits that should be overwritten. The mask must be defined in the lower half of the 16 bits.
ui16Val is the value to write. The value must be defined in the lower half of the 16 bits.
Returns
None
 {
     uint32_t ui32RegOffset;
     // Check the arguments.
     ASSERT(DDIBaseValid(ui32Base));
     ASSERT(ui32Reg < DDI_SLAVE_REGS);
     ASSERT(!(ui16Val & 0xFF00));
     ASSERT(!(ui16Mask & 0xFF00));
     // Get the correct address of the first register used for setting bits
     // in the DDI slave.
     ui32RegOffset = DDI_O_MASK8B + (ui32Reg << 1) + (ui32Byte << 1);
     // Set the selected bits.
     AuxAdiDdiSafeWrite(ui32Base + ui32RegOffset, (ui16Mask << 8) | ui16Val, 2);
 }
Macro Definition Documentation
#define DDI_ACK 0x00000001
#define DDI_PROTECT 0x00000080
#define DDI_SLAVE_REGS 64
Referenced by DDI16SetValBit(), DDI32BitsClear(), DDI32BitsSet(), DDI32RegRead(), DDI32RegWrite(), and DDI8SetValBit().
#define DDI_SYNC 0x00000000