CC13xx Driver Library: [chipinfo] Chip Info
[chipinfo] Chip Info
System Control
Functions
ProtocolBitVector_t ChipInfo_GetSupportedProtocol_BV (void)
Returns bit vector showing supported protocols.
static bool ChipInfo_SupportsBLE (void)
Returns true if the chip supports the BLE protocol.
static bool ChipInfo_SupportsIEEE_802_15_4 (void)
Returns true if the chip supports the IEEE 802.15.4 protocol.
static bool ChipInfo_SupportsPROPRIETARY (void)
Returns true if the chip supports propriatary protocols.
PackageType_t ChipInfo_GetPackageType (void)
Returns package type.
static bool ChipInfo_PackageTypeIs4x4 (void)
Returns true if this is a 4x4mm chip.
static bool ChipInfo_PackageTypeIs5x5 (void)
Returns true if this is a 5x5mm chip.
static bool ChipInfo_PackageTypeIs7x7 (void)
Returns true if this is a 7x7mm chip.
static bool ChipInfo_PackageTypeIsWAFER (void)
Returns true if this is a wafer sale chip (naked die).
static bool ChipInfo_PackageTypeIsWCSP (void)
Returns true if this is a WCSP chip (flip chip).
static bool ChipInfo_PackageTypeIs7x7Q1 (void)
Returns true if this is a 7x7 Q1 chip.
static uint32_t ChipInfo_GetDeviceIdHwRevCode (void)
Returns the internal chip HW revision code.
static uint32_t ChipInfo_GetMinorHwRev (void)
Returns minor hardware revision number.
static uint32_t ChipInfo_GetUserId (void)
Returns the 32 bits USER_ID field.
ChipType_t ChipInfo_GetChipType (void)
Returns chip type.
ChipFamily_t ChipInfo_GetChipFamily (void)
Returns chip family member.
static bool ChipInfo_ChipFamilyIs_CC13x0 (void)
Returns true if this chip is member of the CC13x0 family.
static bool ChipInfo_ChipFamilyIs_CC26x0 (void)
Returns true if this chip is member of the CC26x0 family.
static bool ChipInfo_ChipFamilyIs_CC26x0R2 (void)
Returns true if this chip is member of the CC26x0R2 family.
static bool ChipInfo_ChipFamilyIs_CC26x1 (void)
Returns true if this chip is member of the CC26x1 family.
static bool ChipInfo_ChipFamilyIs_CC13x2_13x4_26x2_26x4 (void)
Returns true if this chip is member of the CC13x2, CC13x4, CC26x2, CC26x4 family.
HwRevision_t ChipInfo_GetHwRevision (void)
Returns chip HW revision.
static bool ChipInfo_HwRevisionIs_1_0 (void)
Returns true if HW revision for this chip is 1.0.
static bool ChipInfo_HwRevisionIs_2_0 (void)
Returns true if HW revision for this chip is 2.0.
static bool ChipInfo_HwRevisionIs_GTEQ_2_0 (void)
Returns true if HW revision for this chip is 2.0 or greater.
static bool ChipInfo_HwRevisionIs_2_1 (void)
Returns true if HW revision for this chip is 2.1.
static bool ChipInfo_HwRevisionIs_GTEQ_2_1 (void)
Returns true if HW revision for this chip is 2.1 or greater.
static bool ChipInfo_HwRevisionIs_2_2 (void)
Returns true if HW revision for this chip is 2.2.
static bool ChipInfo_HwRevisionIs_GTEQ_2_2 (void)
Returns true if HW revision for this chip is 2.2 or greater.
static bool ChipInfo_HwRevisionIs_GTEQ_2_3 (void)
Returns true if HW revision for this chip is 2.3 or greater.
static bool ChipInfo_HwRevisionIs_GTEQ_2_4 (void)
Returns true if HW revision for this chip is 2.4 or greater.
void ThisLibraryIsFor_CC13x0_HwRev20AndLater_HaltIfViolated (void)
Verifies that current chip is CC13x0 HwRev 2.0 or later and never returns if violated.
Enumerations
enum ProtocolBitVector_t { PROTOCOL_Unknown = 0, PROTOCOLBIT_BLE = 0x02, PROTOCOLBIT_IEEE_802_15_4 = 0x04, PROTOCOLBIT_Proprietary = 0x08 }
Enumeration identifying the protocols supported.
enum PackageType_t {
PACKAGE_Unknown = -1, PACKAGE_4x4 = 0, PACKAGE_5x5 = 1, PACKAGE_7x7 = 2,
PACKAGE_WAFER = 3, PACKAGE_WCSP = 4, PACKAGE_7x7_Q1 = 5
}
Package type enumeration.
enum ChipType_t {
CHIP_TYPE_Unknown = -1, CHIP_TYPE_CC1310 = 0, CHIP_TYPE_CC1350 = 1, CHIP_TYPE_CC2620 = 2,
CHIP_TYPE_CC2630 = 3, CHIP_TYPE_CC2640 = 4, CHIP_TYPE_CC2650 = 5, CHIP_TYPE_CUSTOM_0 = 6,
CHIP_TYPE_CUSTOM_1 = 7, CHIP_TYPE_CC2640R2 = 8
}
Chip type enumeration.
enum ChipFamily_t {
FAMILY_Unknown = -1, FAMILY_CC26x0 = 0, FAMILY_CC13x0 = 1, FAMILY_CC26x1 = 2,
FAMILY_CC26x0R2 = 3, FAMILY_CC13x2_13x4_26x2_26x4 = 4
}
Chip family enumeration.
enum HwRevision_t {
HWREV_Unknown = -1, HWREV_1_0 = 10, HWREV_1_1 = 11, HWREV_2_0 = 20,
HWREV_2_1 = 21, HWREV_2_2 = 22, HWREV_2_3 = 23, HWREV_2_4 = 24
}
HW revision enumeration.
Detailed Description
Function Documentation
static bool ChipInfo_ChipFamilyIs_CC13x0 (void) inline static
Returns true if this chip is member of the CC13x0 family.
Returns
Returns true if this chip is member of the CC13x0 family, false otherwise.
Referenced by ThisLibraryIsFor_CC13x0_HwRev20AndLater_HaltIfViolated().
 {
    return ( ChipInfo_GetChipFamily() == FAMILY_CC13x0 );
 }
static bool ChipInfo_ChipFamilyIs_CC13x2_13x4_26x2_26x4 (void) inline static
Returns true if this chip is member of the CC13x2, CC13x4, CC26x2, CC26x4 family.
Returns
Returns true if this chip is member of the CC13x2, CC13x4, CC26x2, CC26x4 family, false otherwise.
 {
    return ( ChipInfo_GetChipFamily() == FAMILY_CC13x2_13x4_26x2_26x4 );
 }
static bool ChipInfo_ChipFamilyIs_CC26x0 (void) inline static
Returns true if this chip is member of the CC26x0 family.
Returns
Returns true if this chip is member of the CC26x0 family, false otherwise.
 {
    return ( ChipInfo_GetChipFamily() == FAMILY_CC26x0 );
 }
static bool ChipInfo_ChipFamilyIs_CC26x0R2 (void) inline static
Returns true if this chip is member of the CC26x0R2 family.
Returns
Returns true if this chip is member of the CC26x0R2 family, false otherwise.
 {
    return ( ChipInfo_GetChipFamily() == FAMILY_CC26x0R2 );
 }
static bool ChipInfo_ChipFamilyIs_CC26x1 (void) inline static
Returns true if this chip is member of the CC26x1 family.
Returns
Returns true if this chip is member of the CC26x1 family, false otherwise.
 {
    return ( ChipInfo_GetChipFamily() == FAMILY_CC26x1 );
 }
ChipFamily_t ChipInfo_GetChipFamily (void)
Returns chip family member.
Returns
Returns ChipFamily_t
Referenced by ChipInfo_ChipFamilyIs_CC13x0(), ChipInfo_ChipFamilyIs_CC13x2_13x4_26x2_26x4(), ChipInfo_ChipFamilyIs_CC26x0(), ChipInfo_ChipFamilyIs_CC26x0R2(), ChipInfo_ChipFamilyIs_CC26x1(), ChipInfo_GetChipType(), and ChipInfo_GetHwRevision().
 {
    uint32_t       waferId                    ;
    ChipFamily_t   chipFam = FAMILY_Unknown   ;
    waferId = (( HWREG( FCFG1_BASE + FCFG1_O_ICEPICK_DEVICE_ID ) &
                                       FCFG1_ICEPICK_DEVICE_ID_WAFER_ID_M ) >>
                                       FCFG1_ICEPICK_DEVICE_ID_WAFER_ID_S ) ;
    if ( waferId == 0xB9BE ) {
       chipFam = FAMILY_CC13x0                ;
    }
    return ( chipFam );
 }
ChipType_t ChipInfo_GetChipType (void)
Returns chip type.
Returns
Returns ChipType_t
 {
    ChipType_t     chipType       = CHIP_TYPE_Unknown        ;
    ChipFamily_t   chipFam        = ChipInfo_GetChipFamily() ;
    uint32_t       fcfg1UserId    = ChipInfo_GetUserId()     ;
    uint32_t       fcfg1Protocol  = (( fcfg1UserId & FCFG1_USER_ID_PROTOCOL_M ) >>
                                                     FCFG1_USER_ID_PROTOCOL_S ) ;
    if ( chipFam == FAMILY_CC13x0 ) {
       switch ( fcfg1Protocol ) {
       case 0x8 :
          chipType = CHIP_TYPE_CC1310      ;
          break;
       case 0xF :
          chipType = CHIP_TYPE_CC1350      ;
          break;
       }
    }
    return ( chipType );
 }
static uint32_t ChipInfo_GetDeviceIdHwRevCode (void) inline static
Returns the internal chip HW revision code.
Returns
Returns the internal chip HW revision code (in range 0-15)
Referenced by ChipInfo_GetHwRevision().
 {
    // Returns HwRevCode = FCFG1_O_ICEPICK_DEVICE_ID[31:28]
    return ( HWREG( FCFG1_BASE + FCFG1_O_ICEPICK_DEVICE_ID ) >> 28 );
 }
HwRevision_t ChipInfo_GetHwRevision (void)
Returns chip HW revision.
Returns
Returns HwRevision_t
Referenced by ChipInfo_HwRevisionIs_1_0(), ChipInfo_HwRevisionIs_2_0(), ChipInfo_HwRevisionIs_2_1(), ChipInfo_HwRevisionIs_2_2(), ChipInfo_HwRevisionIs_GTEQ_2_0(), ChipInfo_HwRevisionIs_GTEQ_2_1(), ChipInfo_HwRevisionIs_GTEQ_2_2(), ChipInfo_HwRevisionIs_GTEQ_2_3(), and ChipInfo_HwRevisionIs_GTEQ_2_4().
 {
    HwRevision_t   hwRev       = HWREV_Unknown                     ;
    uint32_t       fcfg1Rev    = ChipInfo_GetDeviceIdHwRevCode()   ;
    uint32_t       minorHwRev  = ChipInfo_GetMinorHwRev()          ;
    ChipFamily_t   chipFam     = ChipInfo_GetChipFamily()          ;
    if ( chipFam == FAMILY_CC13x0 ) {
       switch ( fcfg1Rev ) {
       case 0 : // CC13x0 PG1.0
          hwRev = HWREV_1_0;
          break;
       case 2 : // CC13x0 PG2.0 (or later)
          hwRev = (HwRevision_t)(((uint32_t)HWREV_2_0 ) + minorHwRev );
          break;
       }
    }
    return ( hwRev );
 }
static uint32_t ChipInfo_GetMinorHwRev (void) inline static
Returns minor hardware revision number.
The minor revision number is set to 0 for the first market released chip and thereafter incremented by 1 for each minor hardware change.
Returns
Returns the minor hardware revision number (in range 0-127)
Referenced by ChipInfo_GetHwRevision().
 {
    uint32_t minorRev = (( HWREG( FCFG1_BASE + FCFG1_O_MISC_CONF_1 ) &
                              FCFG1_MISC_CONF_1_DEVICE_MINOR_REV_M ) >>
                              FCFG1_MISC_CONF_1_DEVICE_MINOR_REV_S ) ;
    if ( minorRev >= 0x80 ) {
       minorRev = 0;
    }
    return( minorRev );
 }
PackageType_t ChipInfo_GetPackageType (void)
Returns package type.
Returns
Returns PackageType_t
Referenced by ChipInfo_PackageTypeIs4x4(), ChipInfo_PackageTypeIs5x5(), ChipInfo_PackageTypeIs7x7(), ChipInfo_PackageTypeIs7x7Q1(), ChipInfo_PackageTypeIsWAFER(), and ChipInfo_PackageTypeIsWCSP().
 {
    PackageType_t packType = (PackageType_t)((
       HWREG( FCFG1_BASE + FCFG1_O_USER_ID     ) &
                           FCFG1_USER_ID_PKG_M ) >>
                           FCFG1_USER_ID_PKG_S ) ;
    if (( packType < PACKAGE_4x4    ) ||
        ( packType > PACKAGE_7x7_Q1 )    )
    {
       packType = PACKAGE_Unknown;
    }
    return ( packType );
 }
ProtocolBitVector_t ChipInfo_GetSupportedProtocol_BV (void)
Returns bit vector showing supported protocols.
Returns
Returns ProtocolBitVector_t which is a bit vector indicating supported protocols.
Referenced by ChipInfo_SupportsBLE(), ChipInfo_SupportsIEEE_802_15_4(), and ChipInfo_SupportsPROPRIETARY().
 {
    return ((ProtocolBitVector_t)( HWREG( PRCM_BASE + 0x1D4 ) & 0x0E ));
 }
static uint32_t ChipInfo_GetUserId (void) inline static
Returns the 32 bits USER_ID field.
How to decode the USER_ID filed is described in the Technical Reference Manual (TRM)
Returns
Returns the the 32 bits USER_ID field
Referenced by ChipInfo_GetChipType().
 {
    return ( HWREG( FCFG1_BASE + FCFG1_O_USER_ID ));
 }
static bool ChipInfo_HwRevisionIs_1_0 (void) inline static
Returns true if HW revision for this chip is 1.0.
Returns
Returns true if HW revision for this chip is 1.0, false otherwise.
 {
    return ( ChipInfo_GetHwRevision() == HWREV_1_0 );
 }
static bool ChipInfo_HwRevisionIs_2_0 (void) inline static
Returns true if HW revision for this chip is 2.0.
Returns
Returns true if HW revision for this chip is 2.0, false otherwise.
 {
    return ( ChipInfo_GetHwRevision() == HWREV_2_0 );
 }
static bool ChipInfo_HwRevisionIs_2_1 (void) inline static
Returns true if HW revision for this chip is 2.1.
Returns
Returns true if HW revision for this chip is 2.1, false otherwise.
 {
    return ( ChipInfo_GetHwRevision() == HWREV_2_1 );
 }
static bool ChipInfo_HwRevisionIs_2_2 (void) inline static
Returns true if HW revision for this chip is 2.2.
Returns
Returns true if HW revision for this chip is 2.2, false otherwise.
 {
    return ( ChipInfo_GetHwRevision() == HWREV_2_2 );
 }
static bool ChipInfo_HwRevisionIs_GTEQ_2_0 (void) inline static
Returns true if HW revision for this chip is 2.0 or greater.
Returns
Returns true if HW revision for this chip is 2.0 or greater, false otherwise.
Referenced by ThisLibraryIsFor_CC13x0_HwRev20AndLater_HaltIfViolated().
 {
    return ( ChipInfo_GetHwRevision() >= HWREV_2_0 );
 }
static bool ChipInfo_HwRevisionIs_GTEQ_2_1 (void) inline static
Returns true if HW revision for this chip is 2.1 or greater.
Returns
Returns true if HW revision for this chip is 2.1 or greater, false otherwise.
 {
    return ( ChipInfo_GetHwRevision() >= HWREV_2_1 );
 }
static bool ChipInfo_HwRevisionIs_GTEQ_2_2 (void) inline static
Returns true if HW revision for this chip is 2.2 or greater.
Returns
Returns true if HW revision for this chip is 2.2 or greater, false otherwise.
 {
    return ( ChipInfo_GetHwRevision() >= HWREV_2_2 );
 }
static bool ChipInfo_HwRevisionIs_GTEQ_2_3 (void) inline static
Returns true if HW revision for this chip is 2.3 or greater.
Returns
Returns true if HW revision for this chip is 2.3 or greater, false otherwise.
 {
    return ( ChipInfo_GetHwRevision() >= HWREV_2_3 );
 }
static bool ChipInfo_HwRevisionIs_GTEQ_2_4 (void) inline static
Returns true if HW revision for this chip is 2.4 or greater.
Returns
Returns true if HW revision for this chip is 2.4 or greater, false otherwise.
 {
    return ( ChipInfo_GetHwRevision() >= HWREV_2_4 );
 }
static bool ChipInfo_PackageTypeIs4x4 (void) inline static
Returns true if this is a 4x4mm chip.
Returns
Returns true if this is a 4x4mm chip, false otherwise.
 {
    return ( ChipInfo_GetPackageType() == PACKAGE_4x4 );
 }
static bool ChipInfo_PackageTypeIs5x5 (void) inline static
Returns true if this is a 5x5mm chip.
Returns
Returns true if this is a 5x5mm chip, false otherwise.
 {
    return ( ChipInfo_GetPackageType() == PACKAGE_5x5 );
 }
static bool ChipInfo_PackageTypeIs7x7 (void) inline static
Returns true if this is a 7x7mm chip.
Returns
Returns true if this is a 7x7mm chip, false otherwise.
 {
    return ( ChipInfo_GetPackageType() == PACKAGE_7x7 );
 }
static bool ChipInfo_PackageTypeIs7x7Q1 (void) inline static
Returns true if this is a 7x7 Q1 chip.
Returns
Returns true if this is a 7x7 Q1 chip, false otherwise.
 {
    return ( ChipInfo_GetPackageType() == PACKAGE_7x7_Q1 );
 }
static bool ChipInfo_PackageTypeIsWAFER (void) inline static
Returns true if this is a wafer sale chip (naked die).
Returns
Returns true if this is a wafer sale chip, false otherwise.
 {
    return ( ChipInfo_GetPackageType() == PACKAGE_WAFER );
 }
static bool ChipInfo_PackageTypeIsWCSP (void) inline static
Returns true if this is a WCSP chip (flip chip).
Returns
Returns true if this is a WCSP chip, false otherwise.
 {
    return ( ChipInfo_GetPackageType() == PACKAGE_WCSP );
 }
static bool ChipInfo_SupportsBLE (void) inline static
Returns true if the chip supports the BLE protocol.
Returns
Returns true if supporting the BLE protocol, false otherwise.
 {
    return (( ChipInfo_GetSupportedProtocol_BV() & PROTOCOLBIT_BLE ) != 0 );
 }
static bool ChipInfo_SupportsIEEE_802_15_4 (void) inline static
Returns true if the chip supports the IEEE 802.15.4 protocol.
Returns
Returns true if supporting the IEEE 802.15.4 protocol, false otherwise.
 {
    return (( ChipInfo_GetSupportedProtocol_BV() & PROTOCOLBIT_IEEE_802_15_4 ) != 0 );
 }
static bool ChipInfo_SupportsPROPRIETARY (void) inline static
Returns true if the chip supports propriatary protocols.
Returns
Returns true if supporting propriatary protocols, false otherwise.
 {
    return (( ChipInfo_GetSupportedProtocol_BV() & PROTOCOLBIT_Proprietary ) != 0 );
 }
void ThisLibraryIsFor_CC13x0_HwRev20AndLater_HaltIfViolated (void)
Verifies that current chip is CC13x0 HwRev 2.0 or later and never returns if violated.
Returns
None
Referenced by SetupTrimDevice().
 {
    if (( ! ChipInfo_ChipFamilyIs_CC13x0()   ) ||
        ( ! ChipInfo_HwRevisionIs_GTEQ_2_0() )    )
    {
       while(1)
       {
          // This driverlib version is for CC13x0 PG2.0 and later.
          // Do nothing - stay here forever
       }
    }
 }
Enumeration Type Documentation
enum ChipFamily_t
Chip family enumeration.
Enumerator
FAMILY_Unknown
-1 means that the chip's family member is unknown.
FAMILY_CC26x0
0 means that the chip is a CC26x0 family member.
FAMILY_CC13x0
1 means that the chip is a CC13x0 family member.
FAMILY_CC26x1
2 means that the chip is a CC26x1 family member.
FAMILY_CC26x0R2
3 means that the chip is a CC26x0R2 family (new ROM contents).
FAMILY_CC13x2_13x4_26x2_26x4
4 means that the chip is a CC13x2, CC13x4, CC26x2, CC26x4 family member.
              {
    FAMILY_Unknown               = -1,
    FAMILY_CC26x0                =  0,
    FAMILY_CC13x0                =  1,
    FAMILY_CC26x1                =  2,
    FAMILY_CC26x0R2              =  3,
    FAMILY_CC13x2_13x4_26x2_26x4 =  4
 } ChipFamily_t;
enum ChipType_t
Chip type enumeration.
Enumerator
CHIP_TYPE_Unknown
-1 means that the chip type is unknown.
CHIP_TYPE_CC1310
0 means that this is a CC1310 chip.
CHIP_TYPE_CC1350
1 means that this is a CC1350 chip.
CHIP_TYPE_CC2620
2 means that this is a CC2620 chip.
CHIP_TYPE_CC2630
3 means that this is a CC2630 chip.
CHIP_TYPE_CC2640
4 means that this is a CC2640 chip.
CHIP_TYPE_CC2650
5 means that this is a CC2650 chip.
CHIP_TYPE_CUSTOM_0
6 means that this is a CUSTOM_0 chip.
CHIP_TYPE_CUSTOM_1
7 means that this is a CUSTOM_1 chip.
CHIP_TYPE_CC2640R2
4 means that this is a CC2640R2 chip.
              {
    CHIP_TYPE_Unknown       = -1,
    CHIP_TYPE_CC1310        =  0,
    CHIP_TYPE_CC1350        =  1,
    CHIP_TYPE_CC2620        =  2,
    CHIP_TYPE_CC2630        =  3,
    CHIP_TYPE_CC2640        =  4,
    CHIP_TYPE_CC2650        =  5,
    CHIP_TYPE_CUSTOM_0      =  6,
    CHIP_TYPE_CUSTOM_1      =  7,
    CHIP_TYPE_CC2640R2      =  8
 } ChipType_t;
enum HwRevision_t
HW revision enumeration.
Enumerator
HWREV_Unknown
-1 means that the chip's HW revision is unknown.
HWREV_1_0
10 means that the chip's HW revision is 1.0
HWREV_1_1
10 means that the chip's HW revision is 1.0
HWREV_2_0
20 means that the chip's HW revision is 2.0
HWREV_2_1
21 means that the chip's HW revision is 2.1
HWREV_2_2
22 means that the chip's HW revision is 2.2
HWREV_2_3
23 means that the chip's HW revision is 2.3
HWREV_2_4
24 means that the chip's HW revision is 2.4
              {
    HWREV_Unknown     = -1,
    HWREV_1_0         = 10,
    HWREV_1_1         = 11,
    HWREV_2_0         = 20,
    HWREV_2_1         = 21,
    HWREV_2_2         = 22,
    HWREV_2_3         = 23,
    HWREV_2_4         = 24
 } HwRevision_t;
enum PackageType_t
Package type enumeration.
Note
Packages available for a specific device are shown in the device datasheet.
Enumerator
PACKAGE_Unknown
-1 means that current package type is unknown.
PACKAGE_4x4
0 means that this is a 4x4 mm QFN (RHB) package.
PACKAGE_5x5
1 means that this is a 5x5 mm QFN (RSM) package.
PACKAGE_7x7
2 means that this is a 7x7 mm QFN (RGZ) package.
PACKAGE_WAFER
3 means that this is a wafer sale package (naked die).
PACKAGE_WCSP
4 means that this is a 2.7x2.7 mm WCSP (YFV).
PACKAGE_7x7_Q1
5 means that this is a 7x7 mm QFN package with Wettable Flanks.
              {
    PACKAGE_Unknown   = -1,
    PACKAGE_4x4       =  0,
    PACKAGE_5x5       =  1,
    PACKAGE_7x7       =  2,
    PACKAGE_WAFER     =  3,
    PACKAGE_WCSP      =  4,
    PACKAGE_7x7_Q1    =  5
 } PackageType_t;
enum ProtocolBitVector_t
Enumeration identifying the protocols supported.
Note
This is a bit vector enumeration that indicates supported protocols. E.g: 0x06 means that the chip supports both BLE and IEEE 802.15.4
Enumerator
PROTOCOL_Unknown
None of the known protocols are supported.
PROTOCOLBIT_BLE
Bit[1] set, indicates that Bluetooth Low Energy is supported.
PROTOCOLBIT_IEEE_802_15_4
Bit[2] set, indicates that IEEE 802.15.4 is supported.
PROTOCOLBIT_Proprietary
Bit[3] set, indicates that proprietary protocols are supported.
              {
    PROTOCOL_Unknown          = 0   ,
    PROTOCOLBIT_BLE           = 0x02,
    PROTOCOLBIT_IEEE_802_15_4 = 0x04,
    PROTOCOLBIT_Proprietary   = 0x08
 } ProtocolBitVector_t;