/*
 * DO NOT MODIFY. This file is automatically generated during the pre-build
 *                step by the lib_search utility
 */

"C:\ti\simplelink_cc2640r2_sdk_1_40_00_45\source\ti\ble5stack\blelib\ctrl\cc2640_hci_xxbx.a"
"C:\ti\simplelink_cc2640r2_sdk_1_40_00_45\source\ti\ble5stack\blelib\ctrl\cc2640_ll_xxbx.a"
"C:\ti\simplelink_cc2640r2_sdk_1_40_00_45\source\ti\ble5stack\blelib\hci_tl\cc26xx_hci_tl_none.a"
"C:\ti\simplelink_cc2640r2_sdk_1_40_00_45\source\ti\ble5stack\blelib\host\cc26xx_att_xxbx.a"
"C:\ti\simplelink_cc2640r2_sdk_1_40_00_45\source\ti\ble5stack\blelib\host\cc26xx_gap_xxbx.a"
"C:\ti\simplelink_cc2640r2_sdk_1_40_00_45\source\ti\ble5stack\blelib\host\cc26xx_gatt_xxbx.a"
"C:\ti\simplelink_cc2640r2_sdk_1_40_00_45\source\ti\ble5stack\blelib\host\cc26xx_l2cap_xxbx.a"
"C:\ti\simplelink_cc2640r2_sdk_1_40_00_45\source\ti\ble5stack\blelib\host\cc26xx_profiles_xxbx.a"
"C:\ti\simplelink_cc2640r2_sdk_1_40_00_45\source\ti\ble5stack\blelib\host\cc26xx_smp_xxbx.a"
"C:\ti\simplelink_cc2640r2_sdk_1_40_00_45\source\ti\ble5stack\blelib\host\cc26xx_sm_xxbx.a"
